
```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```

# Writing a DMS Plan

In this section we will guide you through the general requirements for the various sections of the DMS plan. It is important to note that it is possible to change your DMS plan. Changes can occur during the [Just-in-Time](https://grants.nih.gov/grants/policy/nihgps/HTML5/section_2/2.5.1_just-in-time_procedures.htm) process or during regular reporting intervals. Thus you need to initially show that you made a plan but it's OK if things change. 

&nbsp;
&nbsp;

These following are the major sections of the plan:

1. **Data type** - describe what data (amount and type) will be generated over the course of funding and what data will or will not be shared
2. **Tools, software, and code** (note code is not required to be shared) - describe in what tools you intend to use to manage and analyze the data
3. **Standards** - describe any standards that you might use for your data and metadata
4. **Data preservation, access, timelines** - describe where the data will be made available and when
5. **Access, distribution, reuse considerations** - describe how you have carefully considered any reasons that might limit sharing
6. **Oversight** - describe who will manage compliance of the DMS plan


## General Requirements

☑️  The plan must be **less than 2 pages**.

- _Follow margin and font formatting restrictions consistent with the rest of the proposal_.

☑️  Nothing confidential or proprietary is in your plan.  

- _Initially DMS plans will not be made public, but they **may be made public** in the future_.

☑️  You are encouraged to talk to the appropriate Program Officer for your respective funding announcement about your plan **before** you submit your grant proposal. 

Keep in mind that your DMS plan will not be reviewed by reviewers, only the budget sections in regard to this will be seen by them. Instead the Program Officer will review your DMS plan to determine if it is reasonable and appropriate or if you need to make changes. 

##  Data Type

### Types and amount data

☑️  Describe what kind of data will be generated over the course of funding.  

☑️  Describe the expected amounts of data for each kind of data.

### Data Sharing

☑️  Describe what data from the project will shared or not shared and justify this decision.

### Metadata, other relevant data, and associated documentation

☑️  List information about metadata.
&nbsp;

☑️  List other possibly relevant data.  

- _This includes data you think is not considered scientific._

☑️  List any relevant information about how you plan to gather the data.

- _For example, this could include study protocols and data collection instruments that you plan to share to make it easier for others to reproduce your work._


## Related Tools, Software and/or Code:

☑️  Describe any software or code you intend to use to process or analyze the data.

- _Provide the names of the tools._
- _Provide how the tools can be accessed._
- _Provide version number of tools and operating systems expected to be used._
- _Provide how long they will be available (if known)._

## Standards:

☑️  Describe the names of any data standards that will be used for your data/metadata to enable easier sharing are repeated use of your data.

- _This could include:_
  - _data formats_
  - _metadata schemas_
  - _content/encoding standards_
  - _standard terminologies_
  - _common data elements_
  - _data dictionaries_
  - _data identifiers_
  - _definitions_
  - _unique identifiers_
  - _other data documentation_

☑️  Describe how these standards will be applied to your data.
&nbsp;

☑️  If no standards exist, justify this.
  
<div class = "dictionary">

**Data Standard**  

An agreed upon set of rules that allow information to be shared and processed in a uniform and consistent manner. This includes representations, formats, and definitions of data. 

Standards vary by discipline. An extensive list of standards you can search can be found [here](https://fairsharing.org/search?fairsharingRegistry=Standard). An example standard is the [MIAME](https://fairsharing.org/FAIRsharing.32b10v) reporting guideline for microarray experiments.

</div>


## Data Preservation, Access, and Associated Timelines

Researchers are expected to try to maximize data sharing while still respecting sharing limitations or restrictions. See the next section if you feel that you have limitations for sharing your data.

<div class = "click_to_expand_block">
<details> <summary> Click here for more requirements for data subject to the [Genomic Data Sharing (GDS) policy](https://sharing.nih.gov/genomic-data-sharing-policy/about-genomic-data-sharing/gds-policy-overview).</summary>

For human genomic data: 

- Investigators are expected to submit data to a repository acceptable under the Genomic Data Sharing Policy. See [Where to Submit Genomic Data](https://sharing.nih.gov/genomic-data-sharing-policy/submitting-genomic-data/where-to-submit-genomic-data). 

- Human genomic data is expected to be shared according to NIH’s [Data Submission and Release Expectations](https://sharing.nih.gov/genomic-data-sharing-policy/submitting-genomic-data/data-submission-and-release-expectations), but no later than the end of the performance period, whichever comes first. 

For Non-human genomic data: 

- Investigators may submit data to any widely used repository. 

- Non-human genomic data is expected to be shared as soon as possible, but no later than the time of an associated publication, or end of the performance period, whichever is first. 

</details>
</div>

### List where the data will be shared

☑️  Describe the repositories for sharing the scientific data, as well as the metadata.

### Methods to make scientific data findable and identifiable

☑️  Describe what you will do to make the data more findable and identifiable. 

- _For example, you could use a persistent unique identifier (PID) or other standard indexing tool. [Zenodo](https://zenodo.org/) can be a useful option for creating digital object identifiers (DOIs)._

### Timeline of scientific data sharing:

☑️  Describe when the scientific data will be made available to others.

- _Recall that data must be shared no later than the time of publication of findings or the end of the award (whatever comes first), however the NIH encourages th the data be shared as early as possible._
- _Renewals can have an updated DMS plan with a different timeline, but if not approved must use previous DMS date._
- _No cost extension also allows for more time._
- _NIH encourages that data be made available as early as possible._

☑️  Describe how long data will be available to others. 
  
- _There is no requirement for how long need to be available, however, note that journals may have requirements and the NIH encourages that data be made available for as long as the data is anticipated to be useful. Furthermore, [Per Section 8.4.2 of the NIH Grants Policy Statement](https://grants.nih.gov/grants/policy/nihgps/html5/section_8/8.4.2_record_retention_and_access.htm), grantee institutions are required to keep data for 3 years following closeout of a grant or contract agreement. Additionally, specific awards may have their own requirements._

☑️  Describe any differences in timelines for different datasets. 

## Access, Distribution, or Reuse Considerations

Describe how you considered various factors that may influence data access or hinder your ability to share the data including:
&nbsp;

☑️  Describe type of informed consent was used or will be used to gather the data.

- _NIH expects informed consent for de-identified cell lines or clinical specimines as well (even if the research does not meet the definition of "human subjects research" under the Common Rule for all data derived from such specimens after January 25th, 2015, the effective date of the [GDS policy](https://sharing.nih.gov/genomic-data-sharing-policy/about-genomic-data-sharing/gds-policy-overview)._

☑️  Describe if access to data related to human subjects will be controlled and how the privacy, rights and confidentiality of these participants will be protected (for example, de-identification methods).

&nbsp;

☑️  Ensure privacy and confidentiality protections consistent with applicable federal, Tribal, state, and local laws, regulations, and policies.
&nbsp;

☑️  Describe any restrictions imposed by federal, Tribal, or state laws, regulations, or policies, or existing or anticipated agreements
&nbsp;

☑️  Describe any other relevant data sharing policies.

- _An example could be the [Genomic Data Sharing (GDS) policy](https://sharing.nih.gov/genomic-data-sharing-policy/about-genomic-data-sharing/gds-policy-overview)._

- _If indeed the data requires compliance with the GDS policy, researchers should indicate if the study should be designated as ["sensitive"](https://grants.nih.gov/grants/guide/notice-files/NOT-OD-19-023.html)._

☑️ Describe any reasons that will limit data sharing (including legal, ethical, or technical concerns, as well as [Institutional Certification](https://sharing.nih.gov/genomic-data-sharing-policy/institutional-certifications/about-institutional-certifications) limitations). Other sharing limitations:

- _This could be because datasets cannot practically be digitized with reasonable efforts, or that privacy or safety of research participants would be compromised or place them at greater risk of re-identification._

- _If data cannot be shared due to an Institutional Certification criteria, for example, the data cannot be shared as expected by the [GDS policy](https://sharing.nih.gov/genomic-data-sharing-policy/about-genomic-data-sharing/gds-policy-overview). Researchers should include this information in their DMS plan and explain why the element cannot be met._


☑️ Describe any consideration for embargo periods or access controls if there are intellectual property concerns, rather than refraining from sharing altogether
      
## Oversight

☑️  Describe who will manage compliance with the DMS plan (include names, titles and roles of all individuals involved).
&nbsp;

☑️  Describe how compliance will be monitored (including frequency of oversight, for example every 3 months).

## List of references for your DMS Plan

The following are scientific papers that can be referenced in your DMS Plan:

- @bonomi_citation_2020 - The promises and challenges associated with sharing genomic data
- @cosgriff_citation_2020 - The promise of shared data for addressing public health emergencies, such as the SARS-CoV-2 pandemic
- @mckiernan_citation_2016 - Data sharing can help advance careers through increases in citations, media attention, potential collaborators, job opportunities, and funding opportunities
- @piwowar_citation_2011 - Investing in data storage and archiving is a good investment of grant funds
- @tenopir_citation_2020 - Most scientists view data sharing favorably; A majority feel lack of access impedes scientific progress
- @vesteghem_citation_2020 - Findable, Accessible, Interoperable and Reusable (FAIR) Data Principles and their importance to precision oncology
- @wilkinson_citation_2016 - Good data management is key to knowledge discovery and innovation; four foundational principles — Findability, Accessibility, Interoperability, and Reusability — can help guide data producers and publishers
