
# About the Authors {-}

These credits are based on our [course contributors table guidelines](https://github.com/jhudsl/OTTR_Template/wiki/How-to-give-credits).

&nbsp;
&nbsp;

|Credits|Names|
|-------|-----|
|**Pedagogy**||
|Lead Content Instructor(s)|[Carrie Wright]| [Ava Hoffman]|
|Content Contributor(s) | Sandy ormbrek, [Elizabeth Humphries], Amy Paguirigan |
|Acknowledgments| Beth Levine |
|**Production**||
|Content Publisher(s)| Helped with publishing platform|
|Content Publishing Reviewer(s)| Reviewed overall content and aesthetics on publishing platform|
|Course Publishing Engineer|[Carrie Wright], [Ava Hoffman]|
|Template Publishing Engineers|[Candace Savonen], [Carrie Wright]|
|Publishing Maintenance Engineer|[Candace Savonen]|
|Technical Publishing Stylists|[Carrie Wright], [Candace Savonen]|
|Package Developers ([ottrpal]) [Candace Savonen], [John Muschelli], [Carrie Wright]|
|**Art and Design**||
|Illustrator(s)|[Ava Hoffman]|
|Figure Artist(s)|[Ava Hoffman], [Carrie Wright]|


&nbsp;


<!-- Author information -->

[Ava Hoffman]: https://www.avahoffman.com/
[John Muschelli]: https://johnmuschelli.com/
[Candace Savonen]: https://www.cansavvy.com/
[Carrie Wright]: https://carriewright11.github.io/
[Elizabeth Humphries]: https://www.linkedin.com/in/elizabeth-humphries-61202a103/

<!-- Links -->

[ottrpal]: https://github.com/jhudsl/ottrpal




