# (PART\*) Appendix {-}


# FAQ {-}

The official NIH DMS Policy FAQ page can be found here: [`https://sharing.nih.gov/faqs#/data-management-and-sharing-policy.htm`](https://sharing.nih.gov/faqs#/data-management-and-sharing-policy.htm){target="_blank"}.


# Additional Resources {-}

## NIH Samples

The NIH provides [example DMS plans](https://sharing.nih.gov/data-management-and-sharing-policy/planning-and-budgeting-for-data-management-and-sharing/writing-a-data-management-and-sharing-plan#sample-plans) to help those who are writing their own. 

## Open Science Framework (OSF) Materials

Librarians and other stakeholders have joined minds to produce guidance materials for researchers, libraries, and librarians to prepare for the 2023 NIH Data Management and Sharing Policy. This working group has created documents for librarians and researchers to use in their institutions as they work to comply with the new policy, including: 

- Glossaries of DMSP & NIH Grant Terminology 

- Checklist for Researchers 

- Policy Readiness Checklist for Librarians 

- Example DMSP & Example DMSP catalog 

You can download the materials and see any updated releases at the [OSF project page](https://osf.io/uadxr/). They have also utilized the [OSF wiki](https://osf.io/uadxr/wiki/home/) to provide descriptions of their outputs, as well as citation information. 

Several other university libraries have also created guides on data management you may find useful, including [Northwestern](https://libguides.northwestern.edu/datamanagement), [Stanford](https://library.stanford.edu/research/data-management-services), [MIT](https://libraries.mit.edu/data-management/), [University of Pittsburgh](https://hsls.libguides.com/data), and [NYU](https://hslguides.med.nyu.edu/data_management).

Feel free to remix these documents to suit your needs with credit to the NIH DMSP Guidance Working Group.

[Learn more about how OSF metadata can support DSMP compliance](https://www.cos.io/blog/new-osf-metadata-to-support-data-sharing-policy-compliance)

[Learn more about how OSF meets desirable characteristics for data repositories](https://www.cos.io/blog/how-osf-meets-desirable-characteristics-for-data-repositories)

## Other Tools

In addition, there are several tools and resources that can help you write data management and sharing plans and help you learn about various policies:

[DMPTool](https://dmptool.org/) - a tool for:

- writing your plan

- associating your plan with your [ORCID](https://orcid.org/) ID

- sharing your plan (if you wish)

- finding other people's plans

- finding guidelines for various sharing policies

[SPARC](http://datasharing.sparcopen.org/data) - a resource for comparing different data sharing policies for a variety of funding agencies in the United States

- includes many different funding agencies, such as the [USDA](https://www.usda.gov/), [NASA](https://www.nasa.gov/), [NSF](https://www.nsf.gov/), [FDA](https://www.fda.gov/), [DOE](https://www.energy.gov/) and more

- note that the NIH data sharing information is currently for the 2003 policy (this will likely change after the new plan goes into effect in Jan 2023)

[Sherpa Juliet](http://v2.sherpa.ac.uk/juliet/) - also a resource for different policies for a variety of funding agencies

- includes information on requirements for **open access publication**, as well as information about data archiving

[Council on Government Relations (COGR)](https://www.cogr.edu/chapter-2-nih-data-management-and-sharing-policy-matrix) - additional information about policy requirements

## Specific Platforms

If you submit your data to dbGaP, you may find this [guide](https://www.whi.org/doc/WHI-dbGaP-Guidelines.pdf) a useful resource.

[Learn more about how the NHGRI AnVIL Platform can help meet DSMP policy requirements](https://terra.bio/anvil-platform-helps-meet-the-new-nih-data-management-and-sharing-policy-requirements/)

# Further Reading {-}

It's always a good idea to refer to the the primary literature! The following are scientific papers that can be referenced in your DMS Plan or read for further context:

&nbsp;
&nbsp;


- @bonomi_citation_2020 - The promises and challenges associated with sharing genomic data
- @cosgriff_citation_2020 - The promise of shared data for addressing public health emergencies, such as the SARS-CoV-2 pandemic
- @mckiernan_citation_2016 - Data sharing can help advance careers through increases in citations, media attention, potential collaborators, job opportunities, and funding opportunities
- @piwowar_citation_2011 - Investing in data storage and archiving is a good investment of grant funds
- @sansone_fairsharing_2019 - FAIRsharing as a community approach to standards, repositories and policies
- @tenopir_citation_2020 - Most scientists view data sharing favorably; A majority feel lack of access impedes scientific progress
- @vesteghem_citation_2020 - Findable, Accessible, Interoperable and Reusable (FAIR) Data Principles and their importance to precision oncology
- @wilkinson_citation_2016 - Good data management is key to knowledge discovery and innovation; four foundational principles — Findability, Accessibility, Interoperability, and Reusability — can help guide data producers and publishers


# Tools Used for This Course  {-}

```{r, echo = FALSE}
devtools::session_info()
```

